services:
  tg-search:
    build: .
    image: haroldli/tg-search:latest
    container_name: tg-search
    restart: unless-stopped
    ports:
      - "6000:6000"
    volumes:
      - ./data:/data/tg-search
    environment:
      - TZ=Asia/Shanghai
