services:
  tg-search:
    build: .
    image: haroldli/tg-search:latest
    container_name: tg-search
    restart: unless-stopped
    ports:
      - "9900:9900"
    volumes:
      - ./data:/data/tg-search
