FROM alpine:3.22

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app

COPY --chmod=755 dist/local/tg-search /usr/local/bin/tg-search
COPY docker/config.yaml /app/config.yaml

EXPOSE 9900
VOLUME ["/data/tg-search"]
ENTRYPOINT ["tg-search"]
